### PR TITLE
fix[wip]: don't fetch web2 addresses if not enabled

### PR DESCRIPTION
**Pull request by Kiryous**
- [ ] fix type issue on NotificationsButton

### CODE REVIEW

**Comment by AlekseiPetrovDev** [comment]
Have a suggestion: squash all work related commits into 1 commit and prettier make as separate comment, in that case will be possible to check changes avoid checking prettier diff. I realised I have the same issue in my PR @Kiryous @fsher what do you think?

**Comment by Kiryous** [comment]
Hey! Do you mean for this PR or a general strategy? Actually if everyone is running "Format on save" with the .prettierrc config, should be always up to date

**Comment by Kiryous** [comment]
@fsher hey! Could you help nail down the type error with channelOptions, please?

**Comment by fsher** [comment]
Sorry for a late reply, what seems to be the problem? @Kiryous

**Pull request closed without merging**
