### PR TITLE
hotfix: full width & height notification center on mobile, remove rel…

### PR DESCRIPTION
**Pull request by Kiryous**
…ative position, calculate top via js

### CODE REVIEW

**Comment by cbosborn** [comment]
@Kiryous is there a way we can use css to accomplish this responsiveness goal?

**Comment by Kiryous** [comment]
> @Kiryous is there a way we can use css to accomplish this responsiveness goal?

I dont't think so. If we use css-only, we use a `position: relative` for proper positioning of notification center, but than we cannot set width 100%. So I propose to go with js for positioning of notification center.

@cbosborn Why do you want to avoid this?

@fsher any thought on this?

**Comment by fsher** [comment]
I wonder if this PR is still relevant, @Kiryous @cbosborn? Might be related to the existing [PR](https://github.com/dialectlabs/react/pull/51)

**Comment by Kiryous** [comment]
> I wonder if this PR is still relevant, @Kiryous @cbosborn? Might be related to the existing [PR](https://github.com/dialectlabs/react/pull/51)

the #51 will replace this one, so I close it

**Pull request closed without merging**
